services:
  project-portfolio-api_production:
    environment:
      - DATABASE_URL
      - JWT_SECRET
      - PORT
      - ITEM_PER_PAGE
      - FRONTEND_URL
      - MAIL_PUBLIC_API_KEY
      - MAIL_SERVICE_ID
      - MAIL_TEMPLATE_FOR_CONTACT
      - MAIL_TEMPLATE_FOR_CREATE_ACCOUNT
      - MAIL_TEMPLATE_FOR_PASSWORD_RESET


    container_name: nestjs-chat-api_production
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: yannisduvignau/project-portfolio-api:production
    restart: always
    ports:
      - 8000:8000
      - 8001:8001