import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export async function seedSkill() {
  // Liste des catégories et compétences
  const skillCategories = [
    {
      title: 'Développement Web',
      title_en: 'Web development',
      slug: 'web_development',
      masqued: false,
      priority: 1,
      skills: [
        {
          title: 'HTML',
          title_en: 'HTML',
          iconSrc: 'html.svg',
          description: 'Structure page web',
          description_en: 'Web page structure',
          stars: 5,
          masqued: false,
          priority: 1,
          slug: 'html',
        },
        {
          title: 'CSS',
          title_en: 'CSS',
          iconSrc: 'css.svg',
          description: 'Style page web',
          description_en: 'Web page style',
          stars: 5,
          masqued: false,
          priority: 1,
          slug: 'css',
        },
        {
          title: 'Bootstrap',
          title_en: 'Bootstrap',
          iconSrc: 'bootstrap.svg',
          description: 'Style page web',
          description_en: 'Web page style framework',
          stars: 4,
          masqued: false,
          priority: 1,
          slug: 'bootstrap',
        },
        {
          title: 'Tailwind CSS',
          title_en: 'Tailwind CSS',
          iconSrc: 'tailwind.svg',
          description: 'Style page web',
          description_en: 'Web page style framework',
          stars: 5,
          masqued: false,
          priority: 1,
          slug: 'tailwind',
        },
        {
          title: 'JS',
          title_en: 'JS',
          iconSrc: 'js.svg',
          description: 'Intéraction',
          description_en: 'Interaction',
          stars: 5,
          masqued: false,
          priority: 1,
          slug: 'javascript',
        },
        {
          title: 'TS',
          title_en: 'TS',
          iconSrc: 'ts.svg',
          description: 'Intéraction',
          description_en: 'Interaction',
          stars: 4,
          masqued: false,
          priority: 1,
          slug: 'typescript',
        },
        {
          title: 'Framer motion',
          title_en: 'Framer motion',
          iconSrc: 'framer.svg',
          description: 'Animation',
          description_en: 'Animation',
          stars: 4,
          masqued: false,
          priority: 1,
          slug: 'framer_motion',
        },
        {
          title: 'PHP',
          title_en: 'PHP',
          iconSrc: 'php.svg',
          description: 'Serveur',
          description_en: 'Server',
          stars: 5,
          masqued: false,
          priority: 1,
          slug: 'php',
        },
        {
          title: 'Ruby',
          title_en: 'Ruby',
          iconSrc: 'ruby.svg',
          description: 'Serveur',
          description_en: 'Server',
          stars: 3,
          masqued: false,
          priority: 1,
          slug: 'ruby',
        },
        {
          title: 'MySql',
          title_en: 'MySql',
          iconSrc: 'mysql.svg',
          description: 'Base de données',
          description_en: 'Database',
          stars: 5,
          masqued: false,
          priority: 1,
          slug: 'mysql',
        },
        {
          title: 'Postgre Sql',
          title_en: 'Postgre Sql',
          iconSrc: 'psql.svg',
          description: 'Base de données',
          description_en: 'Database',
          stars: 5,
          masqued: false,
          priority: 1,
          slug: 'postgresql',
        },
        {
          title: 'Mongo DB',
          title_en: 'Mongo DB',
          iconSrc: 'mongodb.svg',
          description: 'Base de données',
          description_en: 'Database',
          stars: 3,
          masqued: false,
          priority: 1,
          slug: 'mongodb',
        },
      ],
    },
    {
      title: 'Développement Applicatif',
      title_en: 'App Development',
      masqued: false,
      priority: 1,
      slug: 'app_development',
      skills: [
        {
          title: 'C++',
          title_en: 'C++',
          iconSrc: 'cpp.png',
          description: 'Programmation logiciel',
          description_en: 'Software programming',
          stars: 5,
          masqued: false,
          priority: 1,
          slug: 'cpp',
        },
        {
          title: 'C',
          title_en: 'C',
          iconSrc: 'c.png',
          description: 'Programmation système',
          description_en: 'System programming',
          stars: 3,
          masqued: false,
          priority: 1,
          slug: 'c',
        },
        {
          title: 'C#',
          title_en: 'C#',
          iconSrc: 'cs.png',
          description: 'Programmation logiciel',
          description_en: 'Software programming',
          stars: 2,
          masqued: false,
          priority: 1,
          slug: 'csharp',
        },
        {
          title: 'Python',
          title_en: 'Python',
          iconSrc: 'python.svg',
          description: 'Programmation de scripts',
          description_en: 'Script programming',
          stars: 5,
          masqued: false,
          priority: 1,
          slug: 'python',
        },
        {
          title: 'JAVA',
          title_en: 'JAVA',
          iconSrc: 'java.svg',
          description: 'Programmation logiciel',
          description_en: 'Software programming',
          stars: 3,
          masqued: false,
          priority: 1,
          slug: 'java',
        },
        {
          title: 'Android',
          title_en: 'Android',
          iconSrc: 'android.svg',
          description: 'Programmation mobile',
          description_en: 'Mobile programming',
          stars: 3,
          masqued: false,
          priority: 1,
          slug: 'android',
        },
      ],
    },
    {
      title: 'Frameworks',
      title_en: 'Frameworks',
      masqued: false,
      priority: 1,
      slug: 'frameworks',
      skills: [
        {
          title: 'Angular JS',
          title_en: 'Angular JS',
          iconSrc: 'angular.svg',
          description: 'Framework JS',
          description_en: 'JS Framework',
          stars: 4,
          masqued: false,
          priority: 1,
          slug: 'angularjs',
        },
        {
          title: 'React JS',
          title_en: 'React JS',
          iconSrc: 'react.svg',
          description: 'Framework JS',
          description_en: 'JS Framework',
          stars: 4,
          masqued: false,
          priority: 1,
          slug: 'reactjs',
        },
        {
          title: 'Laravel',
          title_en: 'Laravel',
          iconSrc: 'laravel.svg',
          description: 'Framework PHP',
          description_en: 'PHP Framework',
          stars: 5,
          masqued: false,
          priority: 1,
          slug: 'laravel',
        },
        {
          title: 'QT',
          title_en: 'QT',
          iconSrc: 'qt.svg',
          description: 'Framework C++',
          description_en: 'C++ Framework',
          stars: 4,
          masqued: false,
          priority: 1,
          slug: 'qt',
        },
        {
          title: 'FastApi',
          title_en: 'FastApi',
          iconSrc: 'fastapi.svg',
          description: 'Framework Python',
          description_en: 'Python Framework',
          stars: 4,
          masqued: false,
          priority: 1,
          slug: 'fastapi',
        },
        {
          title: 'Flutter',
          title_en: 'Flutter',
          iconSrc: 'flutter.svg',
          description: 'Framework Mobile',
          description_en: 'Mobile Framework',
          stars: 2,
          masqued: false,
          priority: 1,
          slug: 'flutter',
        },
        {
          title: 'Rails',
          title_en: 'Rails',
          iconSrc: 'rails.svg',
          description: 'Framework Ruby',
          description_en: 'Ruby Framework',
          stars: 3,
          masqued: false,
          priority: 1,
          slug: 'rails',
        },
        {
          title: 'Jest JS',
          title_en: 'Jest JS',
          iconSrc: 'jest.webp',
          description: 'Framework de Tests',
          description_en: 'Testing Framework',
          stars: 2,
          masqued: false,
          priority: 1,
          slug: 'jestjs',
        },
        {
          title: 'Nest JS',
          title_en: 'Nest JS',
          iconSrc: 'nest.png',
          description: 'Framework JS',
          description_en: 'JS Framework',
          stars: 3,
          masqued: false,
          priority: 1,
          slug: 'nestjs',
        },
      ],
    },
    {
      title: 'Outils de développement',
      title_en: 'Development tools',
      masqued: false,
      priority: 1,
      slug: 'development_tools',
      skills: [
        {
          title: 'Git',
          title_en: 'Git',
          iconSrc: 'git.svg',
          description: 'Versionnage du code',
          description_en: 'Code versionning',
          stars: 5,
          masqued: false,
          priority: 1,
          slug: 'git',
        },
        {
          title: 'Docker',
          title_en: 'Docker',
          iconSrc: 'docker.svg',
          description: 'Conteneur virtuel',
          description_en: 'Virtual containers',
          stars: 5,
          masqued: false,
          priority: 1,
          slug: 'docker',
        },
        {
          title: 'VSCode',
          title_en: 'VSCode',
          iconSrc: 'vscode.svg',
          description: 'IDE',
          description_en: 'IDE',
          stars: 5,
          masqued: false,
          priority: 1,
          slug: 'vscode',
        },
        {
          title: 'IntelliJ',
          title_en: 'IntelliJ',
          iconSrc: 'intellij.svg',
          description: 'IDE',
          description_en: 'IDE',
          stars: 5,
          masqued: false,
          priority: 1,
          slug: 'intellij',
        },
        {
          title: 'Postman',
          title_en: 'Postman',
          iconSrc: 'postman.svg',
          description: 'Requetteur HTTP',
          description_en: 'HTTP requestor',
          stars: 5,
          masqued: false,
          priority: 1,
          slug: 'postman',
        },
        {
          title: 'AWS',
          title_en: 'AWS',
          iconSrc: 'aws.svg',
          description: 'Service CLOUD',
          description_en: 'CLOUD service',
          stars: 4,
          masqued: false,
          priority: 1,
          slug: 'aws',
        },
      ],
    },
    {
      title: 'Cybersécurité',
      title_en: 'Cybersecurity',
      masqued: false,
      priority: 1,
      slug: 'cybersecurity',
      skills: [
        {
          title: 'Wireshark',
          title_en: 'Wireshark',
          iconSrc: 'wireshark.svg',
          description: 'Analyse du trafic réseau',
          description_en: 'Network traffic analysis',
          stars: 5,
          masqued: false,
          priority: 1,
          slug: 'wireshark',
        },
        {
          title: 'Console',
          title_en: 'Console',
          iconSrc: 'cmd.svg',
          description: 'Ligne de commande',
          description_en: 'Command line',
          stars: 5,
          masqued: false,
          priority: 1,
          slug: 'console',
        },
        {
          title: 'Burp Suite',
          title_en: 'Burp Suite',
          iconSrc: 'burpsuite.svg',
          description: 'Tests de pénétration',
          description_en: 'Pentest',
          stars: 3,
          masqued: false,
          priority: 1,
          slug: 'burpsuite',
        },
        {
          title: 'NMap',
          title_en: 'NMap',
          iconSrc: 'nmap.svg',
          description: 'Ligne de commande',
          description_en: 'Command line',
          stars: 3,
          masqued: false,
          priority: 1,
          slug: 'nmap',
        },
        {
          title: 'OWASP',
          title_en: 'OWASP',
          iconSrc: 'owasp.svg',
          description: 'Tests de pénétration',
          description_en: 'Pentest',
          stars: 0,
          masqued: false,
          priority: 1,
          slug: 'owasp',
        },
        {
          title: 'Metasploit',
          title_en: 'Metasploit',
          iconSrc: 'metasploit.png',
          description: 'Tests de pénétration',
          description_en: 'Pentest',
          stars: 0,
          masqued: false,
          priority: 1,
          slug: 'metasploit',
        },
        {
          title: 'OSINT',
          title_en: 'OSINT',
          iconSrc: 'osint.png',
          description: "Collecte d'informations",
          description_en: 'Information gathering',
          stars: 2,
          masqued: false,
          priority: 1,
          slug: 'osint',
        },
        {
          title: 'Cryptographie',
          title_en: 'Cryptography',
          iconSrc: 'crypto.png',
          description: 'Méthodes de cryptage',
          description_en: 'Encryption methods',
          stars: 2,
          masqued: false,
          priority: 1,
          slug: 'cryptography',
        },
        {
          title: 'XSSi',
          title_en: 'XSSi',
          iconSrc: 'xssi.svg',
          description: 'Cross-Site Script Inclusion',
          description_en: 'Cross-Site Script Inclusion',
          stars: 4,
          masqued: false,
          priority: 1,
          slug: 'xssi',
        },
        {
          title: 'SQLi',
          title_en: 'SQLi',
          iconSrc: 'sqli.svg',
          description: 'SQL injection',
          description_en: 'SQL injection',
          stars: 4,
          masqued: false,
          priority: 1,
          slug: 'sqli',
        },
        {
          title: 'CSRF',
          title_en: 'CSRF',
          iconSrc: 'csrf.svg',
          description: 'Cross Site Request Forgery',
          description_en: 'Cross Site Request Forgery',
          stars: 5,
          masqued: false,
          priority: 1,
          slug: 'csrf',
        },
        {
          title: 'Privilege escalation',
          title_en: 'Privilege escalation',
          iconSrc: 'pe.png',
          description: 'Obtenir un accès privilégié',
          description_en: 'Obtain privileged access',
          stars: 5,
          masqued: true,
          priority: 1,
          slug: 'privilege escalation',
        },
        {
          title: 'Social engineering',
          title_en: 'Social engineering',
          iconSrc: 'se.svg',
          description: 'Manipulation psychologique',
          description_en: 'Psychological manipulation',
          stars: 5,
          masqued: true,
          priority: 1,
          slug: 'social_engineering',
        },
        {
          title: 'ARP Spoofing',
          title_en: 'ARP Spoofing',
          iconSrc: 'arp.png',
          description: 'Manipulation des caches',
          description_en: 'Handling caches',
          stars: 5,
          masqued: true,
          priority: 1,
          slug: 'arp_spoofing',
        },
      ],
    },
    {
      title: 'Autres',
      title_en: 'Others',
      masqued: false,
      priority: 1,
      slug: 'others',
      skills: [
        {
          title: 'Figma',
          title_en: 'Figma',
          iconSrc: 'figma.svg',
          description: 'Maquettage',
          description_en: 'Mock-up',
          stars: 5,
          masqued: false,
          priority: 1,
          slug: 'figma',
        },
        {
          title: 'Algorithme',
          title_en: 'Algorithm',
          iconSrc: 'algo.svg',
          description: 'Conception algorithmique',
          description_en: 'Algorithmic design',
          stars: 5,
          masqued: false,
          priority: 1,
          slug: 'algorithme',
        },
        {
          title: 'Scrum',
          title_en: 'Scrum',
          iconSrc: 'scrum.png',
          description: 'Gestion de project Agile',
          description_en: 'Agile project management',
          stars: 5,
          masqued: false,
          priority: 1,
          slug: 'scrum',
        },
        {
          title: 'Conception',
          title_en: 'Conception',
          iconSrc: 'conception.png',
          description: "Mise en place d'un project",
          description_en: 'Setting up a project',
          stars: 4,
          masqued: false,
          priority: 1,
          slug: 'conception',
        },
        {
          title: 'Analyse statistique',
          title_en: 'Statistical analysis',
          iconSrc: 'stats.png',
          description: 'Statistiques de données',
          description_en: 'Data statistics',
          stars: 5,
          masqued: false,
          priority: 1,
          slug: 'statistical_analysis',
        },
        {
          title: 'Ergonomie',
          title_en: 'Ergonomics',
          iconSrc: 'ergo.png',
          description: 'Design UI/UX',
          description_en: 'UI/UX design',
          stars: 5,
          masqued: false,
          priority: 1,
          slug: 'ergonomics',
        },
        {
          title: 'JUnit',
          title_en: 'JUnit',
          iconSrc: 'junit.png',
          description: 'Tests unitaires',
          description_en: 'Unit testing',
          stars: 2,
          masqued: false,
          priority: 1,
          slug: 'junit',
        },
      ],
    },
  ];

  try {
    for (const category of skillCategories) {
      const skillCategory = await prisma.skillCategory.upsert({
        where: { slug: category.slug },
        update: {
          title: category.title,
          title_en: category.title_en,
          slug: category.slug,
          priority: category.priority,
          masqued: category.masqued,
        },
        create: {
          title: category.title,
          title_en: category.title_en,
          slug: category.slug,
          priority: category.priority,
          masqued: category.masqued,
        },
      });

      for (const skill of category.skills) {
        await prisma.skill.upsert({
          where: { slug: skill.slug },
          update: {
            title: skill.title,
            title_en: skill.title_en,
            slug: skill.slug,
            description: skill.description,
            description_en: skill.description_en,
            stars: skill.stars,
            iconSrc: skill.iconSrc,
            categoryId: skillCategory.id,
            masqued: skill.masqued,
          },
          create: {
            title: skill.title,
            title_en: skill.title_en,
            slug: skill.slug,
            description: skill.description,
            description_en: skill.description_en,
            stars: skill.stars,
            iconSrc: skill.iconSrc,
            categoryId: skillCategory.id,
            masqued: skill.masqued,
          },
        });
      }
    }

    console.log('✅ Skills and categories seeded successfully');
  } catch (error) {
    console.error('❌ Error seeding Skills:', error);
  } finally {
    await prisma.$disconnect();
  }
}
